title: MindYoga
description: MindYoga Application.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate

markdown: kramdown
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge
